### ISSUE TITLE
Validation via Go struct tags

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#368] opened 2022-02-08 05:19 UTC
**What is missing?**

Some settings in Cassandra are immutable once a DC, cluster or node is bootstrapped. 

1. It would be good to validate that these aren't changed via a validating webhook.
1. It might be good to keep track of what features can't be changed post DC/cluster/node bootstrap via struct tags attached to the API types.

**Why do we need it?**

Stability - we must ensure that users can't change (e.g.) num_tokens and similar fields after the DC is up.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-130) by [Unito](https://www.unito.io)
┆Issue Number: K8OP-130

**Comment by jsanda** [comment] 2022-02-08 05:26
Is this a duplicate of #121?

**Comment by Miles-Garnsey** [comment] 2022-02-08 05:30
I think it is separate. I'm not sure what will be implemented in #121, but I figured that it will probably be simpler things. This one is really for the harder cases and also focuses on providing a more general mechanism to define (im)mutability via the CRD, rather than writing custom logic to validate specific fields.

**Closed** 2024-11-12 00:51 UTC
