### ISSUE TITLE
Port MCAC default filters to the new metrics endpoint

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#816] opened 2023-01-17 07:59 UTC
Filters will need to be set by default in the new metrics endpoint config, so that we apply the same ones as [with MCAC](https://github.com/k8ssandra/k8ssandra-operator/blob/7f5687f9b78f6189e7094b1c72a2e1913ae43eb5/pkg/telemetry/cassandra_metrics_filters.go#L16-L29).
Metrics names are fairly similar, so it shouldn't be much of a problem.

Filters priority is a little different though, so there could be some converting needed.

**Comment by Miles-Garnsey** [comment] 2023-01-30 01:00
I was about to assign myself, but I don't understand the point:

> Filters priority is a little different though, so there could be some converting needed.

I'll try to do some research into how MCAC handles this and see if I can figure it out.

**Comment by Miles-Garnsey** [comment] 2023-01-30 02:46
So I've been reading through the latest [PR](https://github.com/k8ssandra/management-api-for-apache-cassandra/pull/256/files) on the new metrics agent, and piecing together how the [current filtering](https://github.com/k8ssandra/k8ssandra-operator/blob/7f5687f9b78f6189e7094b1c72a2e1913ae43eb5/pkg/telemetry/cassandra_metrics_filters.go#L16-L29) works.

It looks like we want to drop everything with `__origname__` `deny:org.apache.cassandra.metrics.Table`, `deny:org.apache.cassandra.metrics.table`, unless it is explicitly allowed [here](https://github.com/k8ssandra/k8ssandra-operator/blob/7f5687f9b78f6189e7094b1c72a2e1913ae43eb5/pkg/telemetry/cassandra_metrics_filters.go#L16-L29).

Not 100% sure if that's correct but I'll start work to make that happen since I think I have bandwidth for it.

**Comment by Miles-Garnsey** [comment] 2023-01-30 09:11
Reproducing conversations from offline:

Having done some more research and worked up a draft PR, I'm not quite sure how to proceed on this. 

It looks like our implementation of the RelabelConfig that we pass to MAAC doesn't support relabelling (at least until [this PR](https://github.com/k8ssandra/management-api-for-apache-cassandra/pull/256) is merged), only `keep` and `drop` actions (see [here](https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/bugfix/source-labels/management-api-agent-common/src/main/java/io/k8ssandra/metrics/builder/filter/FilteringSpec.java#L24)).

Assuming that these function the same way that Prometheus' actions work, it isn't clear to me how we can combine both keeps and drops to drop everything in `org\\.apache\\.cassandra\\.metrics\\.Table.*` and `org\\.apache\\.cassandra\\.metrics\\.table.*` while retaining the specified metrics.

The only way to do this would be to condense all 11 metrics that we currently want to retain into a single line of regex (along the lines of `org\\.apache\\.cassandra\\.metrics\\.Table\\.(?!.*live_ss_table_count|.*LiveSSTableCount|.*live_disk_space_used)` or similar). But this seems less than perfectly maintainable. 

@adejanovski is going to investigate further with a view to deciding whether we try to merge the replacements PR, or take some other approach.

**Closed** 2023-03-08 22:56 UTC
Labels: in-progress
