### ISSUE TITLE
K8SSAND-935 ⁃ Enable auth by default

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#170] opened 2021-09-29 20:45 UTC
**What is missing?**

In K8ssandra 1.x authentication is enabled by default, it should also be the default for K8ssandraClusters deployed by the operator.

**Why do we need it?**

To support best practices.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-935) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆fixVersions: k8ssandra-operator-v1.0.0-beta.1
┆friendlyId: K8SSAND-935
┆priority: Medium

**Comment by adutra** [comment] 2021-12-16 10:46
In order to get a more fine-grained picture of what needs to be done, I analyzed what happens in K8ssandra 1.x when `.Values.cassandra.auth.enabled`  is set to true, and what needs to be done in K8ssandra 2.x to get a similar behavior.

### Effects on secret generation

- Cassandra superuser + secret generated
- if Reaper enabled, a reaper superuser + secret  is also generated
- if Medusa enabled, a medusa superuser + secret is also generated
- if Stargate enabled, a stargate superuser + secret is also generated

#### Action items for K8ssandra 2.x

- Cassandra and Reaper superuser + secret are currently generated by default => skip generation if auth disabled.
- I believe Medusa superuser + secret will also be generated by default (@adejanovski can confirm) => skip generation if auth disabled
- Stargate: no superuser + secret currently generated => generate if auth enabled?
  - @jsanda what is this stargate user useful for? The secret is generated and the superuser upserted, but Stargate itself does not use it. Is this intended for drivers to authenticate using this secret?

### Effects on cassandra.yaml

If auth enabled the following is added:

```
authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer
```

Otherwise the following:

```
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
```

Secondary auth properties also have effects on cassandra.yaml – regardless of whether auth is enabled or not. The following is always added:

```
role_manager: CassandraRoleManager
roles_validity_in_ms: {{ .Values.cassandra.auth.cacheValidityPeriodMillis }}
roles_update_interval_in_ms: {{ .Values.cassandra.auth.cacheUpdateIntervalMillis }}
permissions_validity_in_ms: {{ .Values.cassandra.auth.cacheValidityPeriodMillis }}
permissions_update_interval_in_ms: {{ .Values.cassandra.auth.cacheUpdateIntervalMillis }}
credentials_validity_in_ms: {{ .Values.cassandra.auth.cacheValidityPeriodMillis }}
credentials_update_interval_in_ms: {{ .Values.cassandra.auth.cacheUpdateIntervalMillis }}
```

#### Action items for K8ssandra 2.x

- Add authenticator, authorizer and role_manager to cassandra.yaml
  - There are commented fields for these already in the CassandraYaml struct
- Add validity and update settings to cassandra.yaml
  - They are already defined in the `Auth` struct but not used yet.

### Effects on additional jvm options

2 properties are added:

```
-Dcassandra.system_distributed_replication_dc_names={{ $datacenter.name }}
-Dcassandra.system_distributed_replication_per_dc={{ min 5 $datacenter.size }}
```

#### Action items for K8ssandra 2.x

- @jsanda these are currently always added in K8ssandra 2.x, see `cassandra.ApplySystemReplication`. Do we need to add logic to skip adding them if auth is disabled?
- Also K8ssandra 1.x uses a minimum of 5 rf, while 2x uses a minimum of 3, see `utils.ComputeSystemReplication`. What should I do?

### Effects on init containers

The `jmx-credentials` init container gets added to each DC pod.

Two env vars are defined: `SUPERUSER_JMX_USERNAME` and `SUPERUSER_JMX_PASSWORD`. This gets tricky if Reaper is enabled, in which case, 2 more env vars are added for Reaper.

#### Action items for K8ssandra 2.x

- Mutualize current Reaper code that adds the `jmx-credentials` init container
- Need to account for `SUPERUSER_JMX_USERNAME` and `SUPERUSER_JMX_PASSWORD` + Reaper vars
- Need to change command depending on whether Reaper is enabled or not.

### Effects on Reaper CRD

The following property gets defined:

```
serverConfig.cassandraBackend.cassandraUserSecretName: {{ include "k8ssandra.reaperUserSecretName" . }}
```

#### Action items for K8ssandra 2.x

- I believe this is already handled by `ReaperClusterTemplate.CassandraUserSecretRef`, since in K8ssandra 2.x the only available backend is the target DC itself. => nothing to do.

### Effects on medusa.ini

If auth is **disabled** the following gets added:

```
cql_username = cassandra
cql_password = cassandra
```

#### Action items for K8ssandra 2.x

- Since #242 is not merged yet I suggest postponing this part of the task to a follow-up PR.

### Effects on Medusa containers

Two env vars are added: `CQL_USERNAME` and `CQL_PASSWORD`.

#### Action items for K8ssandra 2.x

- Since #242 is not merged yet I suggest postponing this part of the task to a follow-up PR.

**Closed** 2022-01-06 20:38 UTC
